let number = '1.1';
console.log(number, typeof number);
number = parseInt(number);
console.log(number, typeof number);
number = number.toString();
console.log(number, typeof number);
number = Number(number);
console.log(number, typeof number);
number = String(number);
console.log(number, typeof number);
number = Boolean(number);
console.log(number, typeof number);
number = 'one';
number = parseInt(number);
console.log(number, typeof number);
console.log(Math.sqrt(-1));
console.log('one' / 1);
console.log(undefined + undefined);
console.log(typeof NaN);
console.log(1 / 0);
console.log(-1 / 0);

